BEGIN
    BEGIN
        INSERT INTO BLOOD_BANK (BLOOD_BANK_ID, LOCATION_ID, CAPACITY, BLOOD_BANK_NAME)
        VALUES (1, 101, 5000, 'Red Cross Central Blood Bank');
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
 
    BEGIN
        INSERT INTO BLOOD_BANK (BLOOD_BANK_ID, LOCATION_ID, CAPACITY, BLOOD_BANK_NAME)
        VALUES (2, 102, 4500, 'Apollo Hospital Blood Center');
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
 
    BEGIN
        INSERT INTO BLOOD_BANK (BLOOD_BANK_ID, LOCATION_ID, CAPACITY, BLOOD_BANK_NAME)
        VALUES (3, 103, 4000, 'LifeCare Blood Bank');
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
 
    BEGIN
        INSERT INTO BLOOD_BANK (BLOOD_BANK_ID, LOCATION_ID, CAPACITY, BLOOD_BANK_NAME)
        VALUES (4, 104, 5500, 'Medanta Blood Collection Unit');
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
 
    BEGIN
        INSERT INTO BLOOD_BANK (BLOOD_BANK_ID, LOCATION_ID, CAPACITY, BLOOD_BANK_NAME)
        VALUES (5, 105, 4800, 'Narayana Health Blood Bank');
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
END;
/