@insert_location.sql
@insert_data_person_type.sql
@insert_data_blood_type.sql
@insert_hospital.sql
@insert_blood_bank.sql
@insert_bbms_user.sql
@insert_hospital_patient.sql
@insert_data_blood_request.sql
@insert_donation.sql