BEGIN
    BEGIN
        INSERT INTO HOSPITAL_PATIENT (
            HOSPITAL_PATIENT_ID, HOSPITAL_ID, USER_ID, ADMISSION_DATE, DISCHARGE_DATE
        ) VALUES (
            501, 201, 1001, TO_DATE('2023-11-01', 'YYYY-MM-DD'), TO_DATE('2023-11-10', 'YYYY-MM-DD')
        );
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
 
    BEGIN
        INSERT INTO HOSPITAL_PATIENT (
            HOSPITAL_PATIENT_ID, HOSPITAL_ID, USER_ID, ADMISSION_DATE, DISCHARGE_DATE
        ) VALUES (
            502, 202, 1002, TO_DATE('2023-12-05', 'YYYY-MM-DD'), TO_DATE('2023-12-12', 'YYYY-MM-DD')
        );
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
 
    BEGIN
        INSERT INTO HOSPITAL_PATIENT (
            HOSPITAL_PATIENT_ID, HOSPITAL_ID, USER_ID, ADMISSION_DATE, DISCHARGE_DATE
        ) VALUES (
            503, 203, 1003, TO_DATE('2024-01-10', 'YYYY-MM-DD'), TO_DATE('2024-01-18', 'YYYY-MM-DD')
        );
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
 
    BEGIN
        INSERT INTO HOSPITAL_PATIENT (
            HOSPITAL_PATIENT_ID, HOSPITAL_ID, USER_ID, ADMISSION_DATE, DISCHARGE_DATE
        ) VALUES (
            504, 201, 1004, TO_DATE('2024-02-01', 'YYYY-MM-DD'), TO_DATE('2024-02-08', 'YYYY-MM-DD')
        );
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
 
    BEGIN
        INSERT INTO HOSPITAL_PATIENT (
            HOSPITAL_PATIENT_ID, HOSPITAL_ID, USER_ID, ADMISSION_DATE, DISCHARGE_DATE
        ) VALUES (
            505, 202, 1005, TO_DATE('2024-03-01', 'YYYY-MM-DD'), TO_DATE('2024-03-05', 'YYYY-MM-DD')
        );
    EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
END;
/