-- Consistent Blood Bank Insertions
BEGIN
    BEGIN INSERT INTO BLOOD_BANK VALUES (1, 101, 5000, 'Red Cross Central Blood Bank'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
    BEGIN INSERT INTO BLOOD_BANK VALUES (2, 102, 4500, 'Apollo Hospital Blood Center'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
    BEGIN INSERT INTO BLOOD_BANK VALUES (3, 103, 4000, 'LifeCare Blood Bank'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
    BEGIN INSERT INTO BLOOD_BANK VALUES (4, 104, 5500, 'Medanta Blood Collection Unit'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
    BEGIN INSERT INTO BLOOD_BANK VALUES (5, 105, 4800, 'Narayana Health Blood Bank'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
    BEGIN INSERT INTO BLOOD_BANK VALUES (6, 106, 4200, 'Sunrise Blood Bank'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
    BEGIN INSERT INTO BLOOD_BANK VALUES (7, 107, 4700, 'Holy Family Blood Center'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
    BEGIN INSERT INTO BLOOD_BANK VALUES (8, 108, 5100, 'Unity Blood Bank'); EXCEPTION WHEN DUP_VAL_ON_INDEX THEN NULL; END;
END;
/